### ISSUE TITLE
Can't inject on resources with the `conduit.io/plane` label.

### ISSUE THREAD

**Issue by olix0r** [runconduit/conduit#201]
Running a command like:
```
:; target/cli/macos/conduit install -n inception -v $(bin/root-tag) |target/cli/macos/conduit inject -v $(bin/root-tag) - |kubectl apply -f -
```

I'd expect us to add the proxy to all conduit pods in the _inception_ namespace.  Unfortunately, we use a single label, `conduit.io/plane` to indicate whether the node is in the control plane.

It shouldn't be a requirement that a pod is only in one plane.

Furthermore, we should be able to run `inject` on pods that already have been injected (i.e. to update the proxy configuration).

I propose moving these labels to annotations so that they are not mutually exclusive.

Something like `conduit.io/data-plane` `conduit.io/control-plane`?

**Comment by siggy** [comment]
## Proposed changes

### Summary

`conduit.io/plane: control` => `conduit.io/control-plane: member`
`conduit.io/controller: conduit` => `conduit.io/mesh: conduit`
`conduit.io/plane: data` => (remove, redundant with `conduit.io/mesh`)

### Before

`conduit.io/plane: control`: app is a member of the control plane
`conduit.io/plane: data`: app has an injected data plane
`conduit.io/controller: conduit`: app is connected to a controller deployed in the `conduit` namespace

#### conduit controller

```yaml
annotations:
  conduit.io/created-by: conduit/cli git-7399df83
labels:
  app: controller
  conduit.io/plane: control
```

#### injected app

```yaml
annotations:
  conduit.io/created-by: conduit/cli git-7399df83
  conduit.io/proxy-version: git-7399df83
labels:
  app: emoji-svc
  conduit.io/controller: conduit
  conduit.io/plane: data
```

### After

`conduit.io/control-plane: member`: app is a member of the control plane
`conduit.io/mesh: conduit`: app has an injected data plane, and is connected to a controller deployed in the `conduit` namespace

#### conduit controller

```yaml
annotations:
  conduit.io/created-by: conduit/cli git-7399df83
labels:
  app: controller
  conduit.io/control-plane: member
```

#### injected app

```yaml
annotations:
  conduit.io/created-by: conduit/cli git-7399df83
  conduit.io/proxy-version: git-7399df83
labels:
  app: emoji-svc
  conduit.io/mesh: conduit
```
