### ISSUE TITLE
Conduit inject prints the whole YAML file when invalid

### ISSUE THREAD

**Issue by pcalcado** [runconduit/conduit#303]
What happens: When the YAML is broken, the CLI prints the correct error message but dumps the whole file
What I expected to happen: Just the error message and return `!=0`. I can see that dump being useful but it should only be there if the user has set `--verbose`.

## Reproducing
Given this file:
```yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: get-test      
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: get-test-deploy-injected-1
  namespace: get-test
spec:
  replicas: 1
  selector:
      matchLabels:
        app: get-test
  template:
    metadata:
          labels:
            app: get-test
    spec:
      containers:
      - name: http-to-grpc-two-replicas-c1
        image: buoyantio/bb:v1
        args: ["terminus", "--grpc-server-port", "9090", "--response-text", "c1"]
        ports:
        - containerPort: 9090
      - name: http-to-grpc-two-replicas-c2
        image: buoyantio/bb:v1
        args: ["terminus", "--grpc-server-port", "8080", "--response-text", "c2"]
        ports:
        - containerPort: 9090
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: get-test-deploy-injected-2
  namespace: get-test
spec:
  replicas: 1
  selector:
      matchLabels:
        app: get-test
  template:
      metadata:
            labels:
              app: get-test
    spec:
      containers:
      - name: http-to-grpc-one-replica-c1
        image: buoyantio/bb:v1
        args: ["terminus", "--grpc-server-port", "9090", "--response-text", "c1"]
        ports:
        - containerPort: 9090
      - name: http-to-grpc-one-replica-c2
        image: buoyantio/bb:v1
        args: ["terminus", "--grpc-server-port", "8080", "--response-text", "c2"]
        ports:
        - containerPort: 9090
```

This is the output:
```shell
pcalcado@arbeitsziege.local$ conduit inject test/get/testdata/to_be_injected_application.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: get-test
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  name: get-test-deploy-injected-1
  namespace: get-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: get-test
  strategy: {}
  template:
    metadata:
      annotations:
        conduit.io/created-by: conduit/cli git-4156af78
        conduit.io/proxy-version: git-4156af78
      creationTimestamp: null
      labels:
        app: get-test
        conduit.io/control-plane-ns: conduit
    spec:
      containers:
      - args:
        - terminus
        - --grpc-server-port
        - "9090"
        - --response-text
        - c1
        image: buoyantio/bb:v1
        name: http-to-grpc-two-replicas-c1
        ports:
        - containerPort: 9090
        resources: {}
      - args:
        - terminus
        - --grpc-server-port
        - "8080"
        - --response-text
        - c2
        image: buoyantio/bb:v1
        name: http-to-grpc-two-replicas-c2
        ports:
        - containerPort: 9090
        resources: {}
      - env:
        - name: CONDUIT_PROXY_LOG
          value: warn,conduit_proxy=info
        - name: CONDUIT_PROXY_CONTROL_URL
          value: tcp://proxy-api.conduit.svc.cluster.local:8086
        - name: CONDUIT_PROXY_CONTROL_LISTENER
          value: tcp://0.0.0.0:4190
        - name: CONDUIT_PROXY_PRIVATE_LISTENER
          value: tcp://127.0.0.1:4140
        - name: CONDUIT_PROXY_PUBLIC_LISTENER
          value: tcp://0.0.0.0:4143
        - name: CONDUIT_PROXY_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: CONDUIT_PROXY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CONDUIT_PROXY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONDUIT_PROXY_DESTINATIONS_AUTOCOMPLETE_FQDN
          value: Kubernetes
        image: gcr.io/runconduit/proxy:git-4156af78
        imagePullPolicy: IfNotPresent
        name: conduit-proxy
        ports:
        - containerPort: 4143
          name: conduit-proxy
        resources: {}
        securityContext:
          runAsUser: 2102
      initContainers:
      - args:
        - --incoming-proxy-port
        - "4143"
        - --outgoing-proxy-port
        - "4140"
        - --proxy-uid
        - "2102"
        - --inbound-ports-to-ignore
        - "4190"
        image: gcr.io/runconduit/proxy-init:git-4156af78
        imagePullPolicy: IfNotPresent
        name: conduit-init
        resources: {}
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          privileged: false
status: {}
---
Error: error converting YAML to JSON: yaml: line 14: did not find expected key
Usage:
  conduit inject [flags] CONFIG-FILE

Flags:
      --api-port uint                   port where the Conduit controller is running (default 8086)
  -v, --conduit-version string          tag to be used for conduit images (default "git-4156af78")
      --control-port uint               proxy port to use for control (default 4190)
  -h, --help                            help for inject
      --image-pull-policy string        Docker image pull policy (default "IfNotPresent")
      --inbound-port uint               proxy port to use for inbound traffic (default 4143)
      --init-image string               Conduit init container image name (default "gcr.io/runconduit/proxy-init")
      --outbound-port uint              proxy port to use for outbound traffic (default 4140)
      --proxy-image string              Conduit proxy container image name (default "gcr.io/runconduit/proxy")
      --proxy-log-level string          log level for the proxy (default "warn,conduit_proxy=info")
      --proxy-uid int                   Run the proxy under this user ID (default 2102)
      --skip-inbound-ports uintSlice    ports that should skip the proxy and send directly to the applicaiton (default [])
      --skip-outbound-ports uintSlice   outbound ports that should skip the proxy (default [])

Global Flags:
  -n, --conduit-namespace string   namespace in which Conduit is installed (default "conduit")
      --verbose                    turn on debug logging

```
