### ISSUE TITLE
Bad things happen when a DaemonSet with hostNetwork:true is deployed

### ISSUE THREAD

**Issue by jpweber** [runconduit/conduit#366]
When deploying a DaemonSet with hostNetwork set to true an assortment of network related issues happened. kube-apiserver was not reachable. Hosts could not be SSHed in to, conduit gui could not connect to conduit components etc. 

I'm raising this issue not because I want to deploy a DaemonSet with conduit injected in to _and_ use hostNetwork. But I don't think it should effectively take down a cluster either. There has to be a way to protect from this. To replicate the issue deploy the manifest below.

This occurred in the following environment.
k8s 1.9.3
ubuntu 16.04

```
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  labels:
    app: node-exporter
    name: node-exporter
  name: node-exporter
spec:
  clusterIP: None
  ports:
  - name: scrape
    port: 9100
    protocol: TCP
  selector:
    app: node-exporter
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  template:
    metadata:
      labels:
        app: node-exporter
      name: node-exporter
    spec:
      containers:
      - image: prom/node-exporter
        name: node-exporter
        ports:
        - containerPort: 9100
          hostPort: 9100 #comment these out for it to work
          name: scrape
      hostNetwork: true #comment these out for it to work
      hostPID: true
      tolerations:
        - effect: NoSchedule
          operator: Exists
```
