### ISSUE TITLE
Deployment for Prometheus needs RBAC settings as well

### ISSUE THREAD

**Issue by FaKod** [runconduit/conduit#82]
Got the following log from Container Prometheus of Deployment prometheus

```
time="2017-12-21T09:39:03Z" level=error msg="github.com/prometheus/prometheus/discovery/kubernetes/kubernetes.go:209: Failed to list *v1.Pod: User "system:serviceaccount:conduit:default" cannot list pods in the namespace "conduit". (get pods)" component="kube_client_runtime" source="kubernetes.go:76"
```

Adding f.e. SA conduit-controller to it, fixes the issue

**Comment by klingerf** [comment]
@FaKod Nice catch, and thanks for the fix! We'll review shortly.

**Comment by klingerf** [comment]
This has been merged to master and will go out with the next conduit release. In the meantime, for folks encountering this issue, you can apply the following config file to fix it:

```yaml
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: conduit-prometheus
  namespace: conduit
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: conduit-prometheus
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: conduit-prometheus
  namespace: conduit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: conduit-prometheus
subjects:
- kind: ServiceAccount
  name: conduit-prometheus
  namespace: conduit
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: prometheus
  namespace: conduit
  labels:
    app: prometheus
    conduit.io/plane: control
  annotations:
    conduit.io/created-by: "conduit/cli v0.1.1"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
        conduit.io/plane: control
      annotations:
        conduit.io/created-by: "conduit/cli v0.1.1"
    spec:
      serviceAccount: conduit-prometheus
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      containers:
      - name: prometheus
        ports:
        - name: http
          containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
          readOnly: true
        image: prom/prometheus:v1.8.1
        imagePullPolicy: IfNotPresent
        args:
        - "-storage.local.retention=6h"
        - "-storage.local.memory-chunks=500000"
        - "-config.file=/etc/prometheus/prometheus.yml"

      # TODO remove/replace?
      - name: kubectl
        image: buoyantio/kubectl:v1.6.2
        args: ["proxy", "-p", "8001"]
```

Save that file as `conduit-prometheus-rbac.yaml`, and then run:

1. `conduit install | kubectl apply -f -`
2. `kubectl apply -f conduit-prometheus-rbac.yaml`

To get a conduit configuration that works with RBAC-enabled clusters.
